# Generated by Django 5.0 on 2023-12-27 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fire',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('lat', models.DecimalField(decimal_places=8, default=0, max_digits=10)),
                ('lon', models.DecimalField(decimal_places=8, default=0, max_digits=10)),
                ('startDate', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(choices=[('A', 'Actif'), ('E', 'Eteint'), ('I', 'En intervention')], default='A')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('lat', models.DecimalField(decimal_places=8, default=0, max_digits=10)),
                ('lon', models.DecimalField(decimal_places=8, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('sensor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Simulator.sensor')),
                ('data', models.DecimalField(decimal_places=8, default=0, max_digits=10)),
                ('readingDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
