# Generated by Django 5.0 on 2023-12-20 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Simulator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fire',
            name='coord',
        ),
        migrations.AddField(
            model_name='fire',
            name='xCoord',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='fire',
            name='yCoord',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='Coord',
        ),
    ]
