# Generated by Django 5.0 on 2023-12-20 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Simulator', '0002_remove_fire_coord_fire_xcoord_fire_ycoord_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.DecimalField(decimal_places=8, default=0, max_digits=10)),
                ('y', models.DecimalField(decimal_places=8, default=0, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='fire',
            name='xCoord',
            field=models.DecimalField(decimal_places=8, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fire',
            name='yCoord',
            field=models.DecimalField(decimal_places=8, max_digits=10),
        ),
    ]
