# Generated by Django 5.0 on 2023-12-20 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Simulator', '0003_coord_alter_fire_xcoord_alter_fire_ycoord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coord',
        ),
        migrations.RemoveField(
            model_name='fire',
            name='xCoord',
        ),
        migrations.RemoveField(
            model_name='fire',
            name='yCoord',
        ),
        migrations.AddField(
            model_name='fire',
            name='x_coord',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='fire',
            name='y_coord',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=10),
        ),
    ]
