version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: my-postgres-container
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    #volumes:
    #  - ./ressources/init.sql:/docker-entrypoint-initdb.d/init.sql

  django:
    build:
      context: ./dockerfiles/django
      dockerfile: Dockerfile
    image: django
    container_name: my-django-container
    working_dir: /var/www/html
    entrypoint: ["sh", "-c", "python3 -m pip install -r requirements.txt && python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py loaddata users && python3 manage.py runserver 0.0.0.0:80"]
    links:
      - postgres
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html

  pgadmin:
    build:
      context: ./dockerfiles/pgadmin
      dockerfile: Dockerfile
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: 'no'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    links:
      - postgres
    ports:
      - "5050:80"

volumes:
  src: