#FROM ubuntu:latest

#RUN DEBIAN_FRONTEND=noninteractive
#RUN TZ="Europe/Paris"

#RUN apt update && apt upgrade
#RUN apt-get install -y apache2
#RUN apt-get install -y software-properties-common
#RUN add-apt-repository -y ppa:deadsnakes/ppa
#RUN apt-get install -y python3.11
#RUN apt-get install -y python3-pip
#RUN apt update

FROM python:3.11-bullseye

VOLUME /var/www/html